# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e43e699aab6867075646306abcda7d20ea3a42e9fda0d943c00d676e3a624b2483799c3b3114f27b7e3fc9833d4332ea709edf0d6a925007bad966c9159169bf

test:
  secret_key_base: e836bd42e0b5990146a8c3ca3784e345101ecb57df222acb9076af724d2ebf885d7a91b7e7ee2f6381adfbaa00f962eb82f69fa2ed1bec1fc84192c7399ce43e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
